//import { Gender } from "./gender.js";
var buyingPrice = 10;
var sellingPrice = 15;
var profit = sellingPrice - buyingPrice;
console.log("Profit: " + profit);
// let male: Gender = new Gender(1, "Male");
// male.display();
var scores = [10, 20, 30];
var x = ["String", 10];
console.log(scores);
console.log(x);
